#!/bin/sh

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

NAME=meteogalicia
DAEMON=/usr/bin/loop.sh
DAEMONUSER=root
PIDFILE=/var/run/meteogalicia.pid
DESC="Meteogalicia Daemon"
CONF_NAME=$NAME

start_it_up()
{
  msg "Starting $DESC" I
  start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON"
}

shut_it_down()
{
  #local RETVAL
  #msg "Stopping $DESC" I
  #start-stop-daemon -K -p "$PIDFILE"
  #killall -09 "loop.sh"
  #RETVAL="$?"
  #if [ "$RETVAL" = 2 ]; then
  #  return 2
  #fi
  #rm -f "$PIDFILE"
  #return "$RETVAL"
  return 0
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart|force-reload)
    shut_it_down
    sleep 1
    start_it_up
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
